export const listaCosas = [
  { id: 1, title: "Tus ojos" },
  { id: 2, title: "Tu sonrisa" },
  { id: 3, title: "Lo inteligente que eres" },
  { id: 4, title: "Tu gran corazón" },
  { id: 5, title: "Tus pestañas" },
  { id: 6, title: "Lo amorosa que eres" },
  { id: 7, title: "Tu empatía por los demás" },
  { id: 8, title: "Lo fuerte que eres" },
  { id: 9, title: "Tus brazos" },
  { id: 10, title: "Tu pelo" },
  { id: 11, title: "Tu alegría" },
  { id: 12, title: "Tu positivismo" },
  { id: 13, title: "Tu sentido del humor" },
  { id: 14, title: "Lo buena hermana que eres" },
  { id: 15, title: "Tu responsabilidad" },
  { id: 16, title: "Tu nalga" },
  { id: 17, title: "Lo trabajadora que eres" },
  { id: 18, title: "La forma como me miras" },
  { id: 19, title: "Tus piernas" },
  { id: 20, title: "Como me haces el amor" },
  { id: 21, title: "Como me cuidas" },
  { id: 22, title: "Tus besos" },
  { id: 23, title: "Lo apasionada que eres" },
  { id: 24, title: "Tus abrazos" },
  { id: 25, title: "Lo artista y creativa que eres" },
  { id: 26, title: "Tu amor por el dulce" },
];
